<%@ Page Title="Bond |Customer Master" Language="VB" MasterPageFile="User.master" AutoEventWireup="false"
CodeFile="AgentMaster.aspx.vb" Inherits="Summary_BCYMovement" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <head>
<title>Bond |Customer Master</title>
       
</head>
<div class="page-container">
<div class="pageheader">
<h3>
<i class="glyphicon glyphicon-transfer"></i>Customer Master 
</h3>           
</div>
       
<div id="page-content">                   
<asp:ScriptManager ID="ScriptManager1" runat="server"> 
</asp:ScriptManager>
<asp:UpdatePanel ID="UpdatePanel1" runat="server">
<ContentTemplate>
<div class="page-container" style="margin-left: -5px; margin-right: -5px; margin-top: -15px;">
<asp:Label ID="lblError" runat="server" Text="" ForeColor="red"></asp:Label>
<div class="col-md-3 pull-md-left sidebar" style="padding-top:12px;">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title" style="padding-bottom: 0px !important; ">
<i class="fa fa-cube"></i>&nbsp; Customer Master
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>   
<div class="panel-body">
<asp:Repeater ID="rptnoLIst" runat="server">
<ItemTemplate>
<div>                                                       
<a  href='<%# "AgentMaster.aspx?agentIDView=" & Server.UrlEncode(Encrypt(DataBinder.Eval(Container.DataItem, "agentID")).ToString())%>' target="_blank" ><strong><asp:Label runat="server"  Text='<%#Eval("agentName")%>' ID="lblNONumber" style="text-transform:uppercase;"></asp:Label></strong></a>                                                     
<br /> <asp:Label runat="server" Text='<%#Eval("AddDate")%>' Id="lblDate" style="text-transform:uppercase;"></asp:Label>
<br/>Generated By: &nbsp;<asp:Label runat="server" Text='<%#Eval("Users")%>' Id="lbluser" style="text-transform:uppercase;"></asp:Label>
<br />
<asp:Label runat="server" >----------------------------------</asp:Label>
</div>
</ItemTemplate>
</asp:Repeater>
</div>
</div>                           
</div>

<div class="panel-body">
<div class="row">
                                         
<div class="col-md-9 pull-md-right main-content" >
<fieldset class="register">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title">
Customer Master
                
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>
            
<div class="panel-body">
<asp:Panel ID="Panel2" runat="server" Enabled="true">
<div class="row">
<div class="col-md-3 col-xs-12" >
<div class="form-group text-label" style="text-decoration-color:black">
<b >Customer Code</b>
<asp:TextBox ID="txtcode" Style="text-transform:uppercase" ReadOnly="true" class="form-control text-label"  placeholder="Customer Code" MaxLength="11"
runat="server"   ></asp:TextBox>
</div>
</div>

                            
</div>

                        
<div class="row">
<div class="col-md-12 col-xs-12">
<div class="form-group text-label">
<b  >Customer Name</b>
<asp:TextBox ID="txtagentname" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Customer Name"
runat="server"   ></asp:TextBox>
</div>
</div>
</div>
                            
<div class="row">
<div class="col-md-12 col-xs-12">
<div class="form-group text-label">
<b >Address</b>
<asp:TextBox ID="txtaddress" Style="text-transform:uppercase" class="form-control text-label"    placeholder="Address"  
TextMode="MultiLine"   runat="server"   ></asp:TextBox>
</div>
</div>
</div>
<div class="row">
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >City</b>
<asp:TextBox ID="txtcity" Style="text-transform:uppercase" class="form-control text-label"  placeholder="City"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >State</b>
<asp:DropDownList ID="ddlstste"   Style="text-transform: uppercase;" runat="server" class="form-control text-label">  
                                         
</asp:DropDownList>
</div>
</div>
</div>                                               
</asp:Panel>                      

                                             
</div>

</div>
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title">
Customer Contact Details
                
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>
            
<div class="panel-body">
<asp:Panel ID="Panel1" runat="server" Enabled="true">
<div class="row">
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Contact Person</b>
<asp:TextBox ID="txtcontactper" Style="text-transform:uppercase" class="form-control text-label"    placeholder="Contact Person" MaxLength="11"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Person Designation</b>
<asp:TextBox ID="txtperdestinston" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Person Designation"
runat="server"   ></asp:TextBox>
</div>
</div>

</div>

<div class="row">
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Contact Number 1</b>
<asp:TextBox ID="txtnumber1" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidatePhoneNo()"  placeholder="999 999 9999" MaxLength="11"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Contact Number 2</b>
<asp:TextBox ID="txtnumber2" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidatePhoneNo()"  placeholder="999 999 9999" MaxLength="11"
runat="server"   ></asp:TextBox>
</div>
</div>

</div>

<div class="row">
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Fax Number</b>
<asp:TextBox ID="txtfax" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Fax Number"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Mobile Number</b>
<asp:TextBox ID="txtmobile" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidatePhoneNo()"  placeholder="999 999 9999" MaxLength="11"
runat="server"   ></asp:TextBox>
</div>
</div>

</div>
<div class="row">
                                   
<div class="col-md-12 col-xs-12">
<div class="form-group text-label">
<b  >Email ID</b>
<asp:TextBox ID="txtemail" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Email ID"
runat="server"   ></asp:TextBox>
</div>
</div>
</div>


</asp:Panel>

</div>  

</div>

<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title">
Account Details
<%--<i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>
<div class="panel-body">
<asp:Panel ID="Panel4" runat="server" Enabled="true">
                                
<div class="row">
                             
<div class="col-md-3 col-xs-12">
<div class="form-group text-label">
<b  >Storage Weeks</b>
<asp:TextBox ID="txtstorageweeks" Style="text-transform:uppercase" onkeypress="return ValidateNumber()" class="form-control text-label"  placeholder="Storage Weeks"
runat="server"   ></asp:TextBox>
</div>
</div>
       <div class="col-md-3 col-xs-12">
<div class="form-group text-label">
<b >Insurance Weeks</b>
<asp:TextBox ID="txtinsuranceweeks" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateNumber()"   placeholder="Insurance Weeks" runat="server"   ></asp:TextBox>
</div>
</div>                   

<div class="col-md-2 col-xs-12">
<div class="form-group text-label">
<b >Size 20/Area</b>
<asp:TextBox ID="txtsize20perarea" Style="text-transform:uppercase" class="form-control text-label"  onkeypress="return ValidateNumber()"  placeholder="Size 20" runat="server"   ></asp:TextBox>
</div>
</div> 
    <div class="col-md-2 col-xs-12">
<div class="form-group text-label">
<b >Size 40/Area</b>
<asp:TextBox ID="txtsize40perarea" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateNumber()"   placeholder="Size 20" runat="server"   ></asp:TextBox>
</div>
</div> 
    <div class="col-md-2 col-xs-12">
<div class="form-group text-label">
<b >Size 45/Area</b>
<asp:TextBox ID="txt45perarea" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateNumber()"   placeholder="Size 20" runat="server"   ></asp:TextBox>
</div>
</div> 
</div>
                      
                     
</asp:Panel>
</div>
</div>


<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title">
Other
<%--<i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>
<asp:Label ID="lblagentID" Visible="false" runat="server" Text=""></asp:Label>
<asp:Label ID="lblcode" Visible="false" runat="server" Text=""></asp:Label>
<asp:Label ID="lblagentname" Visible="false" runat="server" Text=""></asp:Label>
<div class="panel-body">
<asp:Panel ID="Panel3" runat="server" Enabled="true">
                                
<div class="row">
                             
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Tally Ledger Name</b>
<asp:TextBox ID="txtledger" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Tally Ledger Name"
runat="server"   ></asp:TextBox>
</div>
</div>
                          
</div>

<div class="row">
<div class="col-md-12 col-xs-12">
<div class="form-group text-label">
<b >Remark</b>
<asp:TextBox ID="txtremarks" Style="text-transform:uppercase" class="form-control text-label"    placeholder="Remarks"  
TextMode="MultiLine"   runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-md-6 col-xs-12">
<div class="form-group text-label" style="padding-top:22px;">
<asp:CheckBox ID="chkisActive" runat="server" Checked="true" />
<asp:hiddenfield ID="hdlocation" runat="server" Value="0" />
<asp:Label ID="IsActiveLabel" runat="server" AssociatedControlID="chkisActive" CssClass="inline"> Is Active?</asp:Label>
</div>
</div>

</div>
                      
                     
</asp:Panel>
</div>
</div>
                           

<div class="modal fade control-label" id="myModalforupdate" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-sm">
<asp:UpdatePanel ID="UpdatePanel3" runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
<ContentTemplate>
<div class="modal-content">
<div class="modal-header">
<center>
<span><i runat="server" id="I3" class="fa fa-5x fa-check-circle-o text-success"></i></span>
<br />
<h4 class="modal-title">

<asp:Label ID="lblSession" CssClass="control-label" Font-Bold="true" runat="server" Text=""></asp:Label></h4>
</center>
</div>
<div class="modal-footer">
                   
<a href="AgentMaster.aspx" class="btn btn-info btn-block">OK</a>
                                
</div>
</div>
                    
</ContentTemplate>
             
</asp:UpdatePanel>
</div>
</div>
                         

</fieldset>
                  
<div class="row">
<div class="col-sm-1">
<div class="form-group" style="padding-top:15px">
<asp:Button ID="btnSave" class="btn btn-primary " runat="server" OnClick="btnSave_Click" 
Text="Save"  OnClientClick="return ValidationSave()"  />
</div>
                                              
                                      
</div>
                       
<div class="col-sm-1" style="padding-left:18px;">
<div class="form-group" style="padding-top:15px">
                           
<a href="AgentMaster.aspx" id="btnclear" runat="server" class="btn btn-primary ">
Clear
</a> 
                              
</div>
                                              
                                      
</div>
<div class="col-sm-5 pull-right" style="padding-top:25px;">
<div class="form-group">
<a href="AgentSummary.aspx" target="_blank"><b style="color:blue">Click here to view Customer Summary</b> </a>
</div>
</div>
                         
</div>

</div>
</div>
                               
</div>
                           
                          
                     
                       
                       
</div>
                 
</ContentTemplate>
</asp:UpdatePanel>
</div>
       
         
</div>
   
<script type="text/javascript">
function ValidationSave() {
var txtcode = document.getElementById('<%= txtcode.ClientID%>').value;
var txtagentname = document.getElementById('<%= txtagentname.ClientID%>').value;                   

var blResult = Boolean;
blResult = true;

<%--if (txtcode == "") {
document.getElementById('<%= txtcode.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}--%>

if (txtagentname == "") {
document.getElementById('<%= txtagentname.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}
 
//alert('hi')
if (blResult == false) {
alert('Please fill the required fields!');
}
return blResult;
}
</script>         

<script type="text/javascript">
function ValidatePhoneNo() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 43 || event.keyCode == 32 || event.keyCode == 40 || event.keyCode == 41)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>

<script type="text/javascript">
function ValidateQty() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}
function ValidateNumber() {
    //alert('hii')
    if ((event.keyCode > 47 && event.keyCode < 58))
        return event.returnValue;
    return event.returnValue = '';
}
function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>

<script type="text/javascript">
function Validatevalue() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>
     
<script type="text/javascript">
function ValidateDuty() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>

<script type="text/javascript">

$(document).ready(function () {

//alert('hi')
$('.dummy1').datepicker({
format: 'dd-mm-yyyy',
todayHighlight: true,
autoclose: true,
allowInputToggle: true,

})

});

</script>

<script type="text/javascript">

$(document).ready(function () {

//alert('hi')
$('.dummy2').datepicker({
format: 'dd-mm-yyyy',
todayHighlight: true,
autoclose: true,
allowInputToggle: true,


})




});

</script>

<script type="text/javascript">

$(document).ready(function () {

//alert('hi')
$('.dummy3').datepicker({
format: 'dd-mm-yyyy',
todayHighlight: true,
autoclose: true,
allowInputToggle: true,


})




});

</script>

<script type="text/javascript">

$(document).ready(function () {

//alert('hi')
$('.dummy').datepicker({
format: 'dd-mm-yyyy',
todayHighlight: true,
autoclose: true,
allowInputToggle: true,



})




});

</script>

</asp:Content>
