<%@ Page Title="Bond | Gate Pass " Language="VB" MasterPageFile="User.master" AutoEventWireup="false"
CodeFile="BondGatePasss.aspx.vb" Inherits="Summary_BCYMovement" Culture="en-GB" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <head>
<title>Bond | Gate Pass</title>        
</head>
<div class="page-container">
<div class="pageheader">
<h3>
<i class="glyphicon glyphicon-transfer"></i>Bond Gate Pass
</h3>           
</div>
<div id="page-content">
<asp:ScriptManager ID="ScriptManager1" runat="server">
</asp:ScriptManager>
         
<div class="page-container" style="margin-left: -5px; margin-right: -5px; margin-top: -15px;">
<asp:Label ID="lblError" runat="server" Text="" ForeColor="red"></asp:Label>
<div class="col-md-3 pull-md-left sidebar" style="padding-top:12px;">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title" style="padding-bottom: 0px !important; ">
<i class="fa fa-cube"></i>&nbsp;    Bond Gate Pass
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>   
<div class="panel-body">
<asp:Repeater ID="rptNOLIst" runat="server">
<ItemTemplate>
<div  >
                             
<a  href='<%# "BondGatePasss.aspx?GPNOView=" & Server.UrlEncode(Encrypt(DataBinder.Eval(Container.DataItem, "GPNO")).ToString())%>' target="_blank">                         
<strong><asp:Label runat="server"  Text='<%#Eval("GPNO")%>' ID="lblNONumber" style="text-transform:uppercase;"></asp:Label></strong></a>                                                     
&nbsp;&nbsp; | &nbsp;&nbsp; <asp:Label runat="server" Text='<%#Eval("AddDate")%>' Id="lblDate" style="text-transform:uppercase;"></asp:Label>
<br/>Generated By: &nbsp;<asp:Label runat="server" Text='<%#Eval("Users")%>' Id="lbluser" style="text-transform:uppercase;"></asp:Label>
                                  
<br />
<asp:Label runat="server" >----------------------------------</asp:Label>
</div>
</ItemTemplate>
</asp:Repeater>
</div>
</div>
                           
</div>
<div class="panel-body">

<div class="row">
                                         
<div class="col-md-9 pull-md-right main-content" >
<fieldset class="register">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title">
Bond Gate Pass
                
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>
            
<div class="panel-body">
<asp:Panel ID="Panel2" runat="server" Enabled="true">
<div class="row">
<div class="col-sm-3 col-xs-12" >
<div class="form-group text-label" style="text-decoration-color:black">
<b >Gate Pass No</b>
<asp:TextBox ID="txtGatePasNo" Style="text-transform: uppercase; background-color:#e9e9e9" ReadOnly  class="form-control text-label form-cascade-control"
runat="server" Text="" placeholder="NEW"></asp:TextBox>     
</div>
</div>

<div class="col-sm-3  col-xs-12" ">                                      
<div class="form-group date text-label">
<b >Gate Pass Date</b>
<asp:TextBox ID="txtgateDate"  placeholder="dd-mm-yyyy" TextMode="Date" runat="server"   Class="  form-control text-label"></asp:TextBox>

</div>                        
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
                                        
<b >Bond Ex Tally No</b>
<asp:TextBox ID="txttallyNo" Style="text-transform:uppercase"  AutoPostBack="true"    class="form-control text-label"  placeholder="Bond Ex Tally No"
runat="server" OnTextChanged="txtnocno_TextChanged"  ></asp:TextBox>
</div>
</div>


<div class="col-sm-1 col-xs-6">
                                     
<div class="form-group pull-left" style="padding-top:20px; height: 40px;">
<asp:LinkButton ID="lnksearch" ControlStyle-CssClass='btn btn-primary'  runat="server"
OnClientClick="return OpenItembondgate();">  
<i class=" fa fa-search"     aria-hidden="true"></i> </asp:LinkButton>
</div>
                                  
</div>

<asp:Button ID="btnIndentItem" runat="server" Text="Call Button Click" style="display:none" OnClick="btnIndentItem_Click" />
    <asp:Button ID="btnTrailers" runat="server" Text="Call Button Click" style="display:none" OnClick="btnTrailers_Click" />
                                
<div class="col-sm-2  col-xs-12">                                      
<div class="form-group text-label">
<b >Bond No</b>
<asp:TextBox ID="textbond" runat="server" ReadOnly="true" placeholder="Bond No" class="form-control text-label " AutoPostBack="true">
</asp:TextBox>

</div>
</div>

</div>
</asp:Panel>
<div class="row">
<asp:UpdatePanel ID="UpdatePanel9" runat="server" ChildrenAsTriggers="true" UpdateMode="Conditional">
<ContentTemplate>
<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
                                        
<b >BE No</b>
<asp:TextBox ID="txtbe" Style="text-transform:uppercase" ReadOnly="true"  class="form-control text-label"  placeholder="BE No"
runat="server"   ></asp:TextBox>
</div>
</div>

</ContentTemplate>
</asp:UpdatePanel>

<div class="col-sm-3  col-xs-12"  >                                      
<div class="form-group date text-label">
<b >Bond Date</b>
<asp:TextBox ID="txtbedate"  placeholder="dd-mm-yyyy"  runat="server" TextMode="Date" ReadOnly="true"  Class="   form-control text-label"></asp:TextBox>

</div>                        
</div>
                          
<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b  >Manifested Quantity</b>
<asp:TextBox ID="TxtManifested" Style="text-transform:uppercase" ReadOnly="true"  class="form-control text-label"  placeholder="Manifested Quantity"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b  >Balance Quantity</b>
<asp:TextBox ID="txtBalanec" Style="text-transform:uppercase" ReadOnly="true"  class="form-control text-label"  placeholder="Balance Quantity"
runat="server"   ></asp:TextBox>
</div>
</div>
                            
                              
</div>
<div class="row">
<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Manifested Weight (KGS)</b>
<asp:TextBox ID="txtGross" Style="text-transform:uppercase" ReadOnly="true"  class="form-control text-label"  placeholder="Manifested Weight (KGS)"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Balance Weight(KGS)</b>
<asp:TextBox ID="txtBalanecw" Style="text-transform:uppercase" ReadOnly="true"  class="form-control text-label"  placeholder="Balance Weight(KGS)"
runat="server"   ></asp:TextBox>
</div>
</div>

                              
                           
<div class="col-sm-6  col-xs-12" >
<div class="form-group text-label">
<b>  Importer Name </b>
<asp:textbox ID="txtImporter" AutoPostBack="false" Style="text-transform: uppercase;" runat="server" ReadOnly="true"  class="form-control text-label"  placeholder="Importer Name">
</asp:textbox>   
</div>
</div>
</div>
<div class="col-sm-6  col-xs-12" >
<div class="form-group text-label">
<b>CHA Name</b>
<asp:textbox ID="txtCha" AutoPostBack="false" Style="text-transform: uppercase;" runat="server" ReadOnly="true"  class="form-control text-label" placeholder="CHA Name" >
</asp:textbox>   
</div>
</div>

<div class="row">
<div class="col-sm-6  col-xs-12" >
<div class="form-group text-label">
<b> Description</b>
<asp:textbox  ID="txtDescrlption" AutoPostBack="true" Style="text-transform: uppercase;" runat="server" ReadOnly="true"  class="form-control text-label" placeholder="Description">
</asp:textbox>   
</div>
</div>

</div>
<div class="row">

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Ex BOE No</b>
<asp:TextBox ID="txtexBoe" Style="text-transform:uppercase" ReadOnly="true"  class="form-control text-label"    placeholder="Ex BOE No"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Ex BOE Date</b>
<asp:TextBox ID="txtBoeDate" Style="text-transform:uppercase" ReadOnly="true"  class="form-control text-label"  placeholder="Ex BOE Date"
runat="server"   ></asp:TextBox>
</div>
</div>

                            

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Delivered Quantity</b>
<asp:TextBox ID="txtDelivered" Style="text-transform:uppercase" ReadOnly="true"  class="form-control"    placeholder="Delivered Quantity"  
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b > Delivered Wt</b>
<asp:TextBox ID="txtDeliveredQty" Style="text-transform:uppercase" ReadOnly="true"  class="form-control"    placeholder="Delivered Wt"  
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
                                        
<b >NOC No</b>
<asp:TextBox ID="txtnocno" Style="text-transform:uppercase" ReadOnly="true"  class="form-control text-label"  placeholder="NOC No"
runat="server"   ></asp:TextBox>
</div>
</div>
    
</div>

          
</div>
</div>

                               
<asp:Panel ID="Panel3" runat="server" Enabled="true">
                               
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar" style="padding-left:0px;padding-right:0px">
<div class="panel-heading">
<h3 class="panel-title">
Container Details
                
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>
<div class="panel-body">
<asp:UpdatePanel ID="UpdatePanel3" runat="server" UpdateMode="Conditional">
<ContentTemplate>
<div class="row">
                   
                                                
<div class="col-sm-3 col-xs-12">

<div class="form-group text-label">
<b >Container No</b>
<asp:TextBox ID="txtcontainer" Style="text-transform:uppercase" class="form-control text-label"    placeholder="Container No"  
runat="server" MaxLength="11"></asp:TextBox>
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Quantity</b>
<asp:TextBox ID="textqt" Style="text-transform:uppercase" class="form-control text-label"  onkeypress="return ValidateQty()"  placeholder="Quantity"  
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Size</b>
<asp:DropDownList  ID="ddlsize" AutoPostBack="false" Style="text-transform: uppercase;" runat="server" class="form-control text-label">

<asp:ListItem Value="1">20</asp:ListItem>
<asp:ListItem Value="2">40</asp:ListItem>
<asp:ListItem Value="3">45</asp:ListItem>
</asp:DropDownList>
</div>
</div>
                                                


                                           
                                          
</div>
<div class="row">

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Trailer No</b>
<asp:TextBox ID="txtTrailer" Style="text-transform:uppercase" class="form-control text-label"     placeholder="Trailer No"  
runat="server"   ></asp:TextBox>
</div>
</div>
    <div class="col-sm-1 col-xs-6">
                                     
<div class="form-group pull-left" style="padding-top:20px; height: 40px;">
<asp:LinkButton ID="LinkButton1" ControlStyle-CssClass='btn btn-primary'  runat="server"
OnClientClick="return OpenTrailerbondgate();">  
<i class=" fa fa-search"     aria-hidden="true"></i> </asp:LinkButton>
</div>
                                  
</div>



<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Stuff Quantity</b>
<asp:TextBox ID="txtStuff" Style="text-transform:uppercase" class="form-control text-label"  onkeypress="return ValidateQty()"    placeholder="Stuff Quantity"  
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Stuff Wt</b>
<asp:TextBox ID="txtStufwt" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateQty()"     placeholder="Stuff Wt"  
runat="server"   ></asp:TextBox>
</div>
</div>
                                               

                                           


                                            
                                            
<div class="col-sm-1" style="padding-right:8px;">
<div class="form-group" style="padding-top:20px">
<asp:Button ID="btnadd" class="btn btn-primary " runat="server" OnClick="btnadd_Click"   
Text="Add"  OnClientClick="return ValidationAdd()"/>
</div>
                                              
</div>

</div>  
</ContentTemplate>
</asp:UpdatePanel>

<div class="row">
<asp:UpdatePanel ID="up_grid1" runat="server" UpdateMode="Conditional">
<ContentTemplate>
<div class="row">
<div class="form-group text-label">
<div class="col-sm-4 col-xs-12"  style="margin-left:24px">
<div class="col-sm-4 col-xs-4">
<b>20:</b>
<asp:Label runat="server" ID="lblA" ></asp:Label>
&nbsp</div>
<div class="col-sm-4 col-xs-4">
<b>40:</b>
<asp:Label runat="server" ID="lblB" ></asp:Label>
&nbsp</div>
<div class="col-sm-4 col-xs-4">
<b>45:</b>
<asp:Label runat="server" ID="lblC" ></asp:Label>
&nbsp</div>
</div>
                                 
</div>
</div>
<div class="row">
<div class="col-lg-12 text-label "  style="padding-right:60px;">
<div class="table-responsive scrolling-table-container" style="margin-left:28px;margin-right:0px;">
<asp:GridView ID="grdcontainer" runat="server" ForeColor="Black" CssClass="table table-striped table-bordered table-hover"
AutoGenerateColumns="False" EmptyDataText="No records found!" ShowHeaderWhenEmpty="true"  PageSize="6">
<Columns>
<asp:TemplateField>
<ItemTemplate>
                                                               
                                                            
<asp:LinkButton ID="lnkDelete"  ControlStyle-CssClass='btn btn-danger btn-xs outline' Text="Delete" OnClick="lnkDelete_Click"                                                        
CommandArgument='<%# DataBinder.Eval(Container.DataItem, "Temp_ID")%>' runat="server"  
></asp:LinkButton>

   
</ItemTemplate>
<ItemStyle HorizontalAlign="Left" Width="10px" />
</asp:TemplateField>

<asp:TemplateField HeaderText="Container No" Visible="true"   HeaderStyle-CssClass="center1"   >
<ItemTemplate>

<asp:Label ID="lblContainer" AutoPostBack="true" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "ContainerNo")%>'>'></asp:Label>

</ItemTemplate>
<ItemStyle HorizontalAlign="center" />

</asp:TemplateField>

<asp:TemplateField HeaderText="Qty" Visible="true"   HeaderStyle-CssClass="center1"   >
<ItemTemplate>

<asp:Label ID="lblQty" AutoPostBack="true" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "Qty")%>'>'></asp:Label>

</ItemTemplate>
<ItemStyle HorizontalAlign="center" />

</asp:TemplateField>

<asp:TemplateField HeaderText="Size" Visible="true"   HeaderStyle-CssClass="center1"   >
<ItemTemplate>

<asp:Label ID="lblSize" AutoPostBack="true" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "Container_Size")%>'>'></asp:Label>

</ItemTemplate>
<ItemStyle HorizontalAlign="center" />

</asp:TemplateField>

<asp:TemplateField HeaderText="Trailer No" Visible="true"   HeaderStyle-CssClass="center1"   >
<ItemTemplate>

<asp:Label ID="lblTrailer" AutoPostBack="true" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "TrailerNo")%>'>'></asp:Label>

</ItemTemplate>
<ItemStyle HorizontalAlign="center" />

</asp:TemplateField>

<asp:TemplateField HeaderText="Stuff Qty" Visible="true"   HeaderStyle-CssClass="center1"   >
<ItemTemplate>

<asp:Label ID="lblStufQty" AutoPostBack="true" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "StufQty")%>'>'></asp:Label>

</ItemTemplate>
<ItemStyle HorizontalAlign="center" />

</asp:TemplateField>

<asp:TemplateField HeaderText="Stuff Wt" Visible="true"   HeaderStyle-CssClass="center1"   >
<ItemTemplate>

<asp:Label ID="lblStuf" AutoPostBack="true" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "StufWt")%>'>'></asp:Label>

</ItemTemplate>
<ItemStyle HorizontalAlign="center" />

</asp:TemplateField>
                                                
                                                       
</Columns>

</asp:GridView>
</div>
</div>
</div>
</ContentTemplate>
</asp:UpdatePanel>
</div>
                                             
</div>


</div>
</asp:Panel>

<div class="modal fade control-label" id="myModalforupdate" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-sm">
<asp:UpdatePanel ID="UpdatePanel5" runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
<ContentTemplate>
<div class="modal-content">
<div class="modal-header">
<center>
<span><i runat="server" id="I3" class="fa fa-5x fa-check-circle-o text-success"></i></span>
<br />
<h4 class="modal-title">

<asp:Label ID="lblSession" CssClass="control-label" Font-Bold="true" runat="server" Text=""></asp:Label></h4>
</center>
</div>
<div class="modal-footer">
                   
<%--<a href="BondGatePasss.aspx" class="btn btn-info btn-block">OK</a>--%>
<button class="btn btn-info btn-block" id="saveQuoOK" data-dismiss="modal" runat="server" onserverclick="saveQuoOK_ServerClick" aria-hidden="true">
OK 
</button>
</div>
</div>
                    
</ContentTemplate>
             
</asp:UpdatePanel>
</div>
</div>
<div class="modal fade control-label" id="myModalforupdate1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-sm">
<asp:UpdatePanel ID="UpdatePanel1" runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
<ContentTemplate>
<div class="modal-content">
<div class="modal-header">
<center>
<h4 class="modal-title">
<asp:Label ID="lblquoteApprove"  CssClass="control-label" Font-Bold="true" runat="server" Text=""></asp:Label>
</h4>
</center>
</div>
<div class="modal-footer">
<button class="btn btn-info " id="btnprint" data-dismiss="modal" runat="server" onclick="OpenWOPrint()"  aria-hidden="true">
Yes 
</button>
<a href="BondGatePasss.aspx" class="btn btn-danger ">No</a>
</div>
</div>
</ContentTemplate>
</asp:UpdatePanel>
</div>
</div>          

</fieldset>
                     
<div class="row">
<div class="col-md-1" style="padding-left:16px;">
<div class="form-group" style="padding-top:15px">
<asp:Button ID="btnSave" class="btn btn-primary " runat="server" OnClick="btnSave_Click"     
Text="Save" OnClientClick="return ValidationSearch()"/>
</div>
                                              
                                      
</div>
<div class="col-sm-4 col-xs-12" style="display:none">
<asp:TextBox runat="server" ID="txtgpno" ></asp:TextBox>
                                 

</div>
<div class="col-md-1" style="padding-left:22px;">
<div class="form-group" style="padding-top:0px">
</div>
<a href="BondGatePasss.aspx" id="btnclear" runat="server" class="btn btn-primary ">
Clear
</a>
</div>

                         
</div>

</div>
</div>
                               
</div>
                           
                          
                     
                       
                       
</div>
                 
              
</div>
       
         
</div>
<script type="text/javascript">
var popup;
function OpenWOPrint() {
var txtgpno = document.getElementById('<%= txtgpno.ClientID%>').value;
                

var url = "../Report_Bond/GatePassLogo_Print.aspx?GPNo=" + txtgpno
window.open(url);

}

</script>

<script type="text/javascript">
function ValidationAdd() {
<%--var txtcontainer = document.getElementById('<%= txtcontainer.ClientID%>').value;--%>
<%--  var textqt = document.getElementById('<%= textqt.ClientID%>').value;
var ddlsize = document.getElementById('<%= ddlsize.ClientID%>').value;--%>
var txtTrailer = document.getElementById('<%= txtTrailer.ClientID%>').value;
var txtStuff = document.getElementById('<%= txtStuff.ClientID%>').value;
var txtStufwt = document.getElementById('<%= txtStufwt.ClientID%>').value;


var blResult = Boolean;
blResult = true;

             
if (txtTrailer == "") {
document.getElementById('<%= txtTrailer.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (txtStuff == "") {
document.getElementById('<%= txtStuff.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (txtStufwt == "") {
document.getElementById('<%= txtStufwt.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}


if (blResult == false) {
alert('Please fill the required fields!');
}
return blResult;
}
</script>


<script type="text/javascript">
function ValidationSearch() {
    var txtnocno = document.getElementById('<%= txtnocno.ClientID%>').value;
    var txtDelivered = document.getElementById('<%= txtDelivered.ClientID%>').value;
    var txtDeliveredQty = document.getElementById('<%= txtDeliveredQty.ClientID%>').value;


         
var blResult = Boolean;
blResult = true;

if (txtnocno == "") {
document.getElementById('<%= txtnocno.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}
    if (txtDelivered == "") {
        document.getElementById('<%= txtnocno.ClientID%>').style.borderColor = "red";
        blResult = blResult && false;
    }
    if (txtDeliveredQty == "") {
        document.getElementById('<%= txtnocno.ClientID%>').style.borderColor = "red";
        blResult = blResult && false;
    }
          

if (blResult == false) {
alert('Please enter valid No!');
}
return blResult;
}
</script>

     

<script type="text/javascript">
function Validateduty() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>

<script type="text/javascript">
function ValidateQty() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>

<script type="text/javascript">
function Validatevalue() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>

    
<script type="text/javascript">
var popup;
//alert('hi')
function OpenItembondgate() {
//alert('hi')
    var url = "Gatepasssearch.aspx"
//window.open(url);
popup = window.open(url, "Popup", "width=800,height=550");
popup.focus();
}
</script>
     <script type="text/javascript">
         var popup;
         //alert('hi')

         function OpenTrailerbondgate() {
             //alert('hi')
             var txtnocno = document.getElementById('<%= txtnocno.ClientID%>').value;

             var blResult = Boolean;
             blResult = true;

             if (txtnocno == "") {
                 document.getElementById('<%= txttallyNo.ClientID%>').style.borderColor = "red";
                 blResult = blResult && false;
             }
             if (blResult == false) {
                 alert('Please fill required fields!');
             }
             else
             {
                 var url = "GatePassTrailerSearch.aspx?NOCNo=" + txtnocno
                 //window.open(url);
                 popup = window.open(url, "Popup", "width=800,height=550");
                 popup.focus();
             }
             return blResult;           
         }
</script>

     

      
</asp:Content>
