<%@ Page Title="Bond |  Bond NOC" Language="VB" MasterPageFile="User.master" AutoEventWireup="false"
CodeFile="BondNoc1.aspx.vb" Inherits="Summary_BCYMovement" Culture="en-GB" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
<head>
<title>Bond |  Bond NOC</title>
        
</head>
<div class="page-container">
<div class="pageheader"> 
<h3>
<i class="glyphicon glyphicon-transfer"></i>Bond NOC 
</h3>
           
</div>
       

        
<div id="page-content">            
       
<asp:ScriptManager ID="ScriptManager1" runat="server">
</asp:ScriptManager>
<%--<asp:UpdatePanel ID="UpdatePanel1" runat="server">
<ContentTemplate>--%>
<div class="page-container" style="margin-left: -5px; margin-right: -5px; margin-top: -15px;">
<asp:Label ID="lblError" runat="server" Text="" ForeColor="red"></asp:Label>
<div class="col-md-3 pull-md-left sidebar" style="padding-top:12px;">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title" style="padding-bottom: 0px !important; ">
<i class="fa fa-cube"></i>&nbsp;    Bond - NOC
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>   <div class="panel-body" >
<asp:Repeater ID="rptnoLIst" runat="server">
<ItemTemplate>
<div  >
                             
<a  href='<%# "BondNoc1.aspx?NOCNoView=" & Server.UrlEncode(Encrypt(DataBinder.Eval(Container.DataItem, "NOCNo")).ToString())%>' target="_blank" ><strong><asp:Label runat="server"  Text='<%#Eval("NOCNo")%>' ID="lblNONumber" style="text-transform:uppercase;"></asp:Label></strong></a>                                                     
&nbsp;&nbsp; | &nbsp;&nbsp; <asp:Label runat="server" Text='<%#Eval("AddDate")%>' Id="lblDate" style="text-transform:uppercase;"></asp:Label>
                <br/>Generated By: &nbsp;<asp:Label runat="server" Text='<%#Eval("Users")%>' Id="lbluser" style="text-transform:uppercase;"></asp:Label>
       
<br />
<asp:Label runat="server" >----------------------------------</asp:Label>
</div>
</ItemTemplate>
</asp:Repeater>
</div>
</div>
                           
</div> 
<div class="panel-body">
                                
                                    
<div class="row">
                                         
<div class="col-md-9 pull-md-right main-content" >
<fieldset class="register">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title">
Bond-NOC
                
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>
          
<div class="panel-body">
<asp:Panel ID="Panel2" runat="server" Enabled="true">
<div class="row">
<div class="col-sm-2 col-xs-12" >
<div class="form-group text-label" style="text-decoration-color:black">
<b >NOC No</b>
<asp:TextBox ID="txtnoc" Style="text-transform: uppercase; background-color:#e9e9e9" ReadOnly  class="form-control text-label form-cascade-control"
runat="server" Text="" placeholder="NEW"></asp:TextBox>     
</div>
</div>

                              
<div class="col-sm-3  col-xs-12">                                      
<div class="form-group text-label">
<b >NOC Date</b>
<asp:TextBox ID="txtnocDate"  placeholder="DD-MM-yyyy"   runat="server" TextMode="DateTimeLocal" Class="form-control text-label"></asp:TextBox>
<%--<input type="date" id="txtnocDate" runat="server" class="form-control text-label" />--%>
</div>                        
</div>
                                 
<div class="col-md-4  col-xs-12">                                      
<div class="form-group text-label">
<b >Bond Type</b>
<asp:DropDownList ID="ddlbond" runat="server" class="form-control text-label" AutoPostBack="false">
<asp:ListItem Value="0">--Select--</asp:ListItem>
<asp:ListItem Value="CLOSE BOND">CLOSE BOND</asp:ListItem>
<asp:ListItem Value="OPEN BOND">OPEN BOND</asp:ListItem>
<asp:ListItem Value="CLOSE BOND-SEC-49">CLOSE BOND-SEC-49</asp:ListItem>
<asp:ListItem Value="OPEN BOND-SEC-49">OPEN BOND-SEC-49</asp:ListItem>
</asp:DropDownList>

</div>
</div>
</div>

<div class="row">
<asp:UpdatePanel runat="server" ID="updatepanelnew" UpdateMode="Conditional">

<ContentTemplate>
                                         
<div class="col-sm-5 col-xs-12">
<div class="form-group text-label">
                                        
<b >BE No</b>
<asp:TextBox ID="txtbe" Style="text-transform:uppercase" AutoPostBack="true"  class="form-control text-label"  placeholder="BE No"
runat="server" OnTextChanged="txtbe_TextChanged" ></asp:TextBox>
</div>
</div>
</ContentTemplate>
</asp:UpdatePanel>
<div class="col-sm-4  col-xs-12" ">                                      
<div class="form-group text-label">
<b >BE Date</b>
<asp:TextBox ID="txtbedate" TextMode="DateTimeLocal" runat="server" Class="form-control text-label"></asp:TextBox>
<%--<input type="date" id="txtbedate"  runat="server" class="form-control text-label" />--%>

</div>                        
</div>
                                    
                                       
</div>
<div class="row">
<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b  >IGM-No</b>
<asp:TextBox ID="txtigm" Style="text-transform:uppercase" class="form-control text-label"  placeholder="IGM-No"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-2 col-xs-12">
<div class="form-group text-label">
<b  >Item-No</b>
<asp:TextBox ID="Txtitem" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Item-No"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-4  col-xs-12"">                                      
<div class="form-group text-label">
                                            
<b>IGM Date</b>
<asp:TextBox ID="txtigmDate"  placeholder="mm-dd-yyyy"  runat="server" TextMode="DateTimeLocal" Class="  form-control text-label"></asp:TextBox>
<%--<input type="date" id="txtigmDate" runat="server" class="form-control text-label" />--%>
</div>
</div>

</div>
                                     
<div class="row">
<div class="col-sm-6  col-xs-12" >
<div class="form-group text-label">
<b>  Customer Name  </b>
<asp:DropDownList ID="ddlCustomer" AutoPostBack="True" Style="text-transform: uppercase;" OnSelectedIndexChanged="ddlCustomer_SelectedIndexChanged" runat="server" class="form-control text-label">
</asp:DropDownList>   
</div>
</div>

<div class="col-sm-6  col-xs-12" >
<div class="form-group text-label">
<b> Importer Name</b>
<asp:DropDownList ID="ddlimport" AutoPostBack="false" Style="text-transform: uppercase;" runat="server" class="form-control text-label">
</asp:DropDownList>   
</div>
</div>

</div>    
              
<div class="row">
                          
<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b > Storage Weeks</b>
<asp:TextBox ID="txtweek" Style="text-transform:uppercase" class="form-control text-label"  AutoPostBack="true" placeholder="Storage Weeks"
runat="server" OnTextChanged="txtweek_TextChanged"  ></asp:TextBox>
</div>
</div>

<div class="col-sm-2 col-xs-12">
<div class="form-group text-label">
<b > Storage Days</b>
<asp:TextBox ID="txtday" ReadOnly="true" Style="text-transform:uppercase" class="form-control text-label "  placeholder="Storage Days"
runat="server"   ></asp:TextBox>
</div>
</div>
                                             
<div class="col-sm-4  col-xs-12"">                                      
<div class="form-group text-label">
                                             
<b >Storage Expiry Date</b>
<asp:TextBox ID="txtexpirydate" ReadOnly="true" placeholder="dd-MM-yyyy"  runat="server" Class="form-control text-label"></asp:TextBox>
<%--<input type="date" id="txtexpirydate" ReadOnly="true" runat="server" class="form-control text-label" />--%>
</div>
</div>
</div>
     <div class="row">
                          
<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b > Insurance Weeks</b>
<asp:TextBox ID="txtinsweeks" Style="text-transform:uppercase" class="form-control text-label"  AutoPostBack="true" placeholder="Insurance Weeks"
runat="server" OnTextChanged="txtinsweeks_TextChanged"  ></asp:TextBox>
</div>
</div>

<div class="col-sm-2 col-xs-12">
<div class="form-group text-label">
<b > Insurance Days</b>
<asp:TextBox ID="txtinsdays" ReadOnly="true" Style="text-transform:uppercase" class="form-control text-label "  placeholder="Insurance Days"
runat="server"   ></asp:TextBox>
</div>
</div>
                                             
<div class="col-sm-4  col-xs-12"">                                      
<div class="form-group text-label">
                                             
<b >Insurance Expiry Date</b>
<asp:TextBox ID="txtinsexpdate" ReadOnly="true" placeholder="dd-MM-yyyy"  runat="server" Class="form-control text-label"></asp:TextBox>
<%--<input type="date" id="txtexpirydate" ReadOnly="true" runat="server" class="form-control text-label" />--%>
</div>
</div>
</div>                           
        
<div class="row">
<div class="col-sm-6  col-xs-12" >
<div class="form-group text-label">
<b>CHA Name</b>
<asp:DropDownList ID="ddlcha" AutoPostBack="false" Style="text-transform: uppercase;" runat="server" class="form-control text-label">
</asp:DropDownList>   
</div>
</div>

<div class="col-sm-6 col-xs-12">
<div class="form-group text-label">
<b >Commodity</b>
<asp:TextBox ID="txtcommodity" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Commodity"
runat="server"   ></asp:TextBox>
</div>
</div>

</div>
<div class="row">
<div class="col-sm-3  col-xs-12" >
<div class="form-group text-label">
<b> Status</b>
<asp:DropDownList ID="ddlstatus" AutoPostBack="false" Style="text-transform: uppercase;" runat="server" class="form-control text-label">
<asp:ListItem Value="0">--Select--</asp:ListItem>
<asp:ListItem Value="FCL">FCL</asp:ListItem>
<asp:ListItem Value="LCL">LCL</asp:ListItem>
</asp:DropDownList>   
</div>
</div>

<div class="col-sm-3  col-xs-12" >
<div class="form-group text-label">
<b> Cargo Type</b>
<asp:DropDownList ID="ddlcargo" AutoPostBack="false" Style="text-transform: uppercase;" runat="server" class="form-control text-label">
<asp:ListItem Value="0">--Select--</asp:ListItem>
<asp:ListItem Value="HAZ">HAZ</asp:ListItem>
<asp:ListItem Value="gen">gen</asp:ListItem>
<asp:ListItem Value="ODC">ODC</asp:ListItem>
</asp:DropDownList>   
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Quantity</b>
<asp:TextBox ID="txtqty" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateQty()"  placeholder="Quantity"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Unit</b>
<%--<asp:TextBox ID="txtunit" Style="text-transform:uppercase" class="form-control text-label"  placeholder="UNIT"
runat="server"   ></asp:TextBox>--%>

<asp:DropDownList ID="ddlunit" Style="text-transform: uppercase;" runat="server" class="form-control text-label">

</asp:DropDownList>
</div>
</div>

</div>

<div class="row">
                            

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Gross Wt(kgs)</b>
<asp:TextBox ID="txtgrosskgs" Style="text-transform:uppercase" class="form-control text-label"   onkeypress="return ValidateQty()"  placeholder="Gross Wt"  
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b > Storage Area(sqm)</b>
<asp:TextBox ID="txtstorsqm" Style="text-transform:uppercase" class="form-control text-label"    placeholder="Storage Area"  
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Value</b>
<asp:TextBox ID="txtvalue" Style="text-transform:uppercase" class="form-control text-label"  onkeypress="return Validatevalue()"  placeholder="Value"  
runat="server"   ></asp:TextBox>
</div>
</div>
<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Duty</b>
<asp:TextBox ID="txtduty" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateDuty()" placeholder="Duty"  
runat="server"   ></asp:TextBox>
</div>
</div>
</div>
<div class="row">
                 
<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
<b >Contact No</b>
<asp:TextBox ID="txtcontact" Style="text-transform:uppercase" class="form-control text-label"   onkeypress="return ValidatePhoneNo()"  placeholder="999 999 9999" MaxLength="10"
runat="server"   ></asp:TextBox>
</div>
</div>
</div>

                       
                          
                        
</asp:Panel>

                        

                                             
</div>
</div>


<asp:Panel ID="Panel3" runat="server" Enabled="true">
                               
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar" style="padding-left:0px;padding-right:0px">
<div class="panel-heading">
<h3 class="panel-title">
Container Details
                
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>

<div class="panel-body">
<asp:UpdatePanel ID="up_grid" runat="server" UpdateMode="Conditional">
    <Triggers>
        <asp:PostBackTrigger ControlID="btnAdd" />
    </Triggers>
<ContentTemplate>
                                        
<div class="row">

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
    <b >Container No</b>
<asp:TextBox ID="txtcontainer" Style="text-transform:uppercase" class="form-control text-label"    placeholder="Container No"  
runat="server" MaxLength="11"></asp:TextBox>
</div>
</div>

                                           
<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
    <b >Quantity</b>
<asp:TextBox ID="textqt" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateQty()" placeholder="Quantity"  
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-sm-3 col-xs-12">
<div class="form-group text-label">
    <b >Size</b>
<asp:DropDownList  ID="ddlsize" AutoPostBack="false" Style="text-transform: uppercase;" runat="server" class="form-control text-label">
<asp:ListItem Value="0">--Select--</asp:ListItem>
<asp:ListItem Value="1">20</asp:ListItem>
<asp:ListItem Value="2">40</asp:ListItem>
<asp:ListItem Value="3">45</asp:ListItem>
</asp:DropDownList>
</div>
</div>

<div class="col-sm-1" style="padding-right:12px;">
<div class="form-group" style="padding-top:18px">
<asp:Button ID="btnAdd" class="btn btn-primary " runat="server" OnClick="btnAdd_Click"   
Text="Add" OnClientClick="return ValidationSearch()"/>
</div>
                                              
</div>
</div>
                           
                                       

<div class="row">
       
                           
<div class="row">
<div class="form-group text-label">
<div class="col-sm-4 col-xs-12"  style="margin-left:24px">
<div class="col-sm-4 col-xs-4">
<b>20:</b>
<asp:Label runat="server" ID="lblA" ></asp:Label>
&nbsp</div>
<div class="col-sm-4 col-xs-4">
<b>40:</b>
<asp:Label runat="server" ID="lblB" ></asp:Label>
&nbsp</div>
<div class="col-sm-4 col-xs-4">
<b>45:</b>
<asp:Label runat="server" ID="lblC" ></asp:Label>
&nbsp</div>
</div>
                                 
</div>
    </div>
   
<div class="row">
<div class="col-lg-12 text-label "  style="padding-right:50px;">
<div class="table-responsive scrolling-table-container" style="margin-left:28px;margin-right:0px;">
<asp:GridView ID="grdcontainer" runat="server" ForeColor="Black" CssClass="table table-striped table-bordered table-hover"
AutoGenerateColumns="False" EmptyDataText="No records found!" ShowHeaderWhenEmpty="true"  PageSize="6">
<Columns>
    <asp:TemplateField>
    <ItemTemplate>                                                                                                                        
        <asp:LinkButton ID="lnkDelete"  ControlStyle-CssClass='btn btn-danger btn-xs outline' Text="Delete" OnClick="lnkDelete_Click"                                                         
            CommandArgument='<%# DataBinder.Eval(Container.DataItem, "AutoIdTemp")%>' runat="server"  
            ></asp:LinkButton>   
    </ItemTemplate>
    <ItemStyle HorizontalAlign="Left" Width="140px" />
</asp:TemplateField>
    <asp:BoundField DataField="Container_Num" HeaderText="Container No"></asp:BoundField>
<asp:BoundField DataField="Qty" HeaderText="Quantity"></asp:BoundField>
<asp:BoundField DataField="Container_Size" HeaderText="Size"></asp:BoundField>
    <%-- <asp:BoundField DataField="Type" HeaderText="Type"></asp:BoundField>--%>
    </Columns>

</asp:GridView>
</div>
</div>
</div>
                            
</div>

</div>
</ContentTemplate>
</asp:UpdatePanel>
</div>
</asp:Panel>

<div class="modal fade control-label" id="myModalforupdate" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-sm">
<asp:UpdatePanel ID="UpdatePanel5" runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
<ContentTemplate>
<div class="modal-content">
<div class="modal-header">
<center>
<span><i runat="server" id="I3" class="fa fa-5x fa-check-circle-o text-success"></i></span>
<br />
<h4 class="modal-title">

<asp:Label ID="lblSession" CssClass="control-label" Font-Bold="true" runat="server" Text=""></asp:Label></h4>
</center>
</div>
<div class="modal-footer">
                   
<a href="BondNoc1.aspx" class="btn btn-info btn-block">OK</a>
                                
</div>
</div>
                    
</ContentTemplate>
             
</asp:UpdatePanel>
</div>
</div>
                         

</fieldset>
                  
<div class="row">
<div class="col-sm-1" style="padding-left:16px;">
<div class="form-group" style="padding-top:15px">
<asp:Button ID="btnSave" class="btn btn-primary " runat="server" OnClick="btnSave_Click"    
Text="Save" OnClientClick="return ValidationSave()"/>
</div>
                                              
                                      
</div>

<div class="col-sm-1" style="padding-left:26px;">
<div class="form-group" style="padding-top:0px">
    </div>
<a href="BondNoc1.aspx" id="btnclear" runat="server" class="btn btn-primary ">
    Clear
</a>
</div>
<div class="col-sm-5 pull-right" style="padding-top:15px;">
<div class="form-group">
<a href="NocSummary.aspx" target="_blank"><b style="color:blue">Click here to view NOC Summary</b> </a>
</div>
</div>
                         
</div>

</div>
</div>
                              
</div>
                           
                          
                     
                       
                       
</div>
                 
<%--  </ContentTemplate>
</asp:UpdatePanel>--%>
</div>
       
         
</div>
<script type="text/javascript">
function ValidationSearch() {
var txtcontainer = document.getElementById('<%= txtcontainer.ClientID%>').value;
var textqt = document.getElementById('<%= textqt.ClientID%>').value;
var ddlsize = document.getElementById('<%= ddlsize.ClientID%>').value;
    document.getElementById('<%= btnAdd.ClientID%>').value = "Please Wait...";
    document.getElementById('<%= btnAdd.ClientID%>').setAttribute("class", "btn btn-primary disabled");

var blResult = Boolean;
blResult = true;

if (txtcontainer == "") {
document.getElementById('<%= txtcontainer.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (textqt == "") {
document.getElementById('<%= textqt.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (ddlsize == 0) {
document.getElementById('<%= ddlsize.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}



if (blResult == false) {
    alert('Please fill the required fields!');
    document.getElementById('<%= btnAdd.ClientID%>').value = "Add";
    document.getElementById('<%= btnAdd.ClientID%>').setAttribute("class", "btn btn-primary");
}
return blResult;
}
</script>

<script type="text/javascript">
function ValidationSave() {
var ddlbond = document.getElementById('<%= ddlbond.ClientID%>').value;
var txtbe = document.getElementById('<%= txtbe.ClientID%>').value;
var Txtigm = document.getElementById('<%= Txtigm.ClientID%>').value;
var ddlCustomer = document.getElementById('<%= ddlCustomer.ClientID%>').value;
var ddlimport = document.getElementById('<%= ddlimport.ClientID%>').value;
var ddlcha = document.getElementById('<%= ddlcha.ClientID%>').value;
var txtcommodity = document.getElementById('<%= txtcommodity.ClientID%>').value;
var txtqty = document.getElementById('<%= txtqty.ClientID%>').value;
var ddlunit = document.getElementById('<%= ddlunit.ClientID%>').value;
var txtstorsqm = document.getElementById('<%= txtstorsqm.ClientID%>').value;
var txtnocDate = document.getElementById('<%= txtnocDate.ClientID%>').value;
var txtbedate = document.getElementById('<%= txtbedate.ClientID%>').value;
var txtigmDate = document.getElementById('<%= txtigmDate.ClientID%>').value;
    var txtexpirydate = document.getElementById('<%= txtexpirydate.ClientID%>').value;
    var txtinsexpdate = document.getElementById('<%= txtinsexpdate.ClientID%>').value;

    document.getElementById('<%= btnSave.ClientID%>').value = "Please Wait...";
    document.getElementById('<%= btnSave.ClientID%>').setAttribute("class", "btn btn-primary disabled");

var blResult = Boolean;
blResult = true;

if (ddlbond == 0) {
document.getElementById('<%= ddlbond.ClientID%>').style.borderColor = "red";
blResult = blResult && false;

}

if (txtbe == "") {
document.getElementById('<%= txtbe.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

<%--if (Txtigm == "") {
document.getElementById('<%= Txtigm.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}--%>

if (ddlCustomer == 0) {
document.getElementById('<%= ddlCustomer.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (ddlimport == 0) {
document.getElementById('<%= ddlimport.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (ddlcha == 0) {
document.getElementById('<%= ddlcha.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (txtcommodity == "") {
document.getElementById('<%= txtcommodity.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (txtstorsqm == "") {
document.getElementById('<%= txtstorsqm.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (ddlunit == 0) {
document.getElementById('<%= ddlunit.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (txtnocDate == "") {
document.getElementById('<%= txtnocDate.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (txtbedate == "") {
document.getElementById('<%= txtbedate.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

<%--if (txtigmDate == "") {
document.getElementById('<%= txtigmDate.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}--%>

if (txtexpirydate == "") {
document.getElementById('<%= txtexpirydate.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}
    if (txtinsexpdate == "") {
        document.getElementById('<%= txtinsexpdate.ClientID%>').style.borderColor = "red";
        blResult = blResult && false;
    }
//alert('hi')
if (blResult == false) {
    alert('Please fill the required fields!');
    document.getElementById('<%= btnSave.ClientID%>').value = "Save";
    document.getElementById('<%= btnSave.ClientID%>').setAttribute("class", "btn btn-primary");
}
return blResult;
}
</script>

<script type="text/javascript">
function ValidatePhoneNo() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 43 || event.keyCode == 32 || event.keyCode == 40 || event.keyCode == 41)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>

<script type="text/javascript">
function ValidateQty() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>

<script type="text/javascript">
function Validatevalue() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>

     
<script type="text/javascript">
function ValidateDuty() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>
<script type="text/javascript">

$(document).ready(function () {

//alert('hi')
$('.dummy1').datepicker({
format: 'dd-mm-yyyy',
todayHighlight: true,
autoclose: true,
allowInputToggle: true,



})




});

</script>
     
</asp:Content>
