<%@ Page Title="Bond |  Godown Master" Language="VB" MasterPageFile="User.master" AutoEventWireup="false"
CodeFile="GodownMaster.aspx.vb" Inherits="Summary_BCYMovement" Culture="en-GB" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
<head>
<title>Bond |  Godown Master</title>
       
</head>
<div class="page-container">
<div class="pageheader">
<h3>
<i class="glyphicon glyphicon-transfer"></i>Godown Master 
</h3>
           
</div>
       
<div id="page-content">
        
       
       
<asp:ScriptManager ID="ScriptManager1" runat="server">
</asp:ScriptManager>
<asp:UpdatePanel ID="UpdatePanel1" runat="server">
<ContentTemplate>
</ContentTemplate>
</asp:UpdatePanel>
<div class="page-container" style="margin-left: -5px; margin-right: -5px; margin-top: -15px;">
<asp:Label ID="lblError" runat="server" Text="" ForeColor="red"></asp:Label>
<div class="col-md-3 pull-md-left sidebar" style="padding-top:12px;">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title" style="padding-bottom: 0px !important; ">
<i class="fa fa-cube"></i>&nbsp;   Godown Master
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>   
<div class="panel-body" >
<asp:Repeater ID="rptnoLIst" runat="server">
<ItemTemplate>
<div  >
                             
                            
<a  href='<%# "GodownMaster.aspx?EntryIDView=" & Server.UrlEncode(Encrypt(DataBinder.Eval(Container.DataItem, "EntryID")).ToString())%>' target="_blank" ><strong><asp:Label runat="server"  Text='<%#Eval("GodownCode")%>' ID="lblNONumber" style="text-transform:uppercase;"></asp:Label></strong></a>                                                     
<br /> <asp:Label runat="server" Text='<%#Eval("AddDate")%>' Id="lblDate" style="text-transform:uppercase;"></asp:Label>
<br/>Generated By: &nbsp;<asp:Label runat="server" Text='<%#Eval("Users")%>' Id="lbluser" style="text-transform:uppercase;"></asp:Label>
<br />
<asp:Label runat="server" >----------------------------------</asp:Label>
</div>
</ItemTemplate>
</asp:Repeater>
</div>
</div>
                           
</div>
<div class="panel-body">

<div class="row">
                                         
<div class="col-md-9 pull-md-right main-content" >
<fieldset class="register">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title">
Godown Details
                
<%--<i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>
            
<div class="panel-body">
<asp:Panel ID="Panel2" runat="server" Enabled="true"> 
<div class="row">
<div class="col-md-4 col-xs-12" >
<div class="form-group text-label" style="text-decoration-color:black">
<b >Center Code</b>
<asp:TextBox ID="txtcode" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Center Code" MaxLength="11"
runat="server"   ></asp:TextBox>
</div>
</div>
                  
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >Godown Code</b>
<asp:TextBox ID="txtgodown" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Godown Code"
runat="server"   ></asp:TextBox>
</div>
</div>
                              
<div class="col-md-4  col-xs-12" ">                                      
<div class="form-group date text-label">
<b >Date Of Possession</b>
<asp:TextBox ID="txtdateof"  placeholder="dd-mm-yyyy " TextMode="Date"  runat="server" Class="  form-control text-label"></asp:TextBox>

</div>                        
</div>
</div>
                                
<div class="row">
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >Warehouse Code</b>
    <asp:DropDownList ID="ddlWarehouse"   Style="text-transform: uppercase;" runat="server"   class="form-control text-label">
</asp:DropDownList>
</div>
</div>
</div>

<div class="row">
<div class="col-md-12 col-xs-12">
<div class="form-group text-label">
<b  >Warehouse Description</b>
<asp:TextBox ID="txtWarehouseDesc" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Warehouse Description"
runat="server"   ></asp:TextBox>
</div>
</div>
                                 
</div>

<div class="row">
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >Constructive Capacity(MT)</b>
<asp:TextBox ID="txtConstrucctive" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateQty()" placeholder="Constructive Capacity"
runat="server"   ></asp:TextBox>
</div>
</div>
                            
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >Thumbrule Capacity(MT)</b>
<asp:TextBox ID="txtThumbrule" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateQty()"  placeholder="Thumbrule Capacity(MT)"
runat="server"   ></asp:TextBox>
</div>
</div>
                                 
</div>
                               
</asp:Panel>
                        
</div>
</div>

<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title">
Dimension In Mtrs
                
<%--<i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>
            
<div class="panel-body">
<asp:Panel ID="Panel1" runat="server" Enabled="true">
<div class="row">
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >Width</b>
<asp:TextBox ID="txtwidth" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateQty()"    placeholder="Width"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >Length</b>
<asp:TextBox ID="txtlenth" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateQty()"  placeholder="Length"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >Height</b>
<asp:TextBox ID="txtHeight" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateQty()"  placeholder="Height"
runat="server"   ></asp:TextBox>
</div>
</div>
    <asp:UpdatePanel ID="UpdatePanel2" UpdateMode="Conditional" runat="server">
<ContentTemplate>
    <div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >Area In SQM</b>
<asp:TextBox ID="txtAreaIn" Style="text-transform:uppercase" OnTextChanged="txtAreaIn_TextChanged" AutoPostBack="true" class="form-control text-label" onkeypress="return ValidateQty()"  placeholder="Area in SQM"
runat="server"   ></asp:TextBox>
</div>
</div>

     <div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >Area In SQFT</b>
<asp:TextBox ID="txtAreaSqft" Style="text-transform:uppercase" ReadOnly="true" class="form-control text-label" onkeypress="return ValidateQty()"  placeholder="Area In SQFT"
runat="server"   ></asp:TextBox>
</div>
</div>
    </ContentTemplate>
        </asp:UpdatePanel>


</div>
                                

                                
                              


</asp:Panel>

</div>  

</div>
                       
<asp:Label ID="lblentryID" Visible="false" runat="server" Text=""></asp:Label>
<asp:Label ID="lblcode" Visible="false" runat="server" Text=""></asp:Label>
<asp:Label ID="lblagentname" Visible="false" runat="server" Text=""></asp:Label>
             
                      
<div class="row">
                            
<div class="col-md-6 col-xs-12">
<div class="form-group text-label" style="padding-top:22px;">
<asp:CheckBox ID="chkisActive" runat="server" Checked="true" />
<asp:hiddenfield ID="hdlocation" runat="server" Value="0" />
<asp:Label ID="IsActiveLabel" runat="server" AssociatedControlID="chkisActive" CssClass="inline"> Is Active?</asp:Label>
</div>
</div>

</div>
                         
                       
                  
<div class="row">
<div class="col-sm-1">
<div class="form-group" style="padding-top:15px">
<asp:Button ID="btnSave" class="btn btn-primary " runat="server" OnClick="btnSave_Click"  
Text="Save"  OnClientClick="return ValidationSave()" />
</div>
                                              
                                      
</div>
                       
<div class="col-sm-1" style="padding-left:14px;">
<div class="form-group" style="padding-top:15px">
                           
<a href="GodownMaster.aspx" id="btnclear" runat="server" class="btn btn-primary ">
Clear
</a> 
                              
</div>
                                              
                                      
</div>
<div class="col-sm-5 pull-right" style="padding-top:25px;">
<div class="form-group">
<a href="GodownSummary.aspx" target="_blank"><b style="color:blue">Click here to view Godown Summary</b> </a>
</div>
</div>
                         
</div>
                               
                         
<div class="modal fade control-label" id="myModalforupdate" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-sm">
<asp:UpdatePanel ID="UpdatePanel3" runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
<ContentTemplate>
<div class="modal-content">
<div class="modal-header">
<center>
<span><i runat="server" id="I3" class="fa fa-5x fa-check-circle-o text-success"></i></span>
<br />
<h4 class="modal-title">

<asp:Label ID="lblSession" CssClass="control-label" Font-Bold="true" runat="server" Text=""></asp:Label></h4>
</center>
</div>
<div class="modal-footer">
                   
<a href="GodownMaster.aspx" class="btn btn-info btn-block">OK</a>
                                
</div>
</div>
                    
</ContentTemplate>
             
</asp:UpdatePanel>
</div>
</div>
               
</fieldset>

</div>
</div>
                               
</div>
                           
                          
                     
                       
                       
</div>
                 
                
</div>
       
         
</div>
   
<script type="text/javascript">
function ValidationSave() {
var txtcode = document.getElementById('<%= txtcode.ClientID%>').value;
var txtgodown = document.getElementById('<%= txtgodown.ClientID%>').value;
    var ddlWarehouse = document.getElementById('<%= ddlWarehouse.ClientID%>').value;
var txtwidth = document.getElementById('<%= txtwidth.ClientID%>').value;
var txtlenth = document.getElementById('<%= txtlenth.ClientID%>').value;
var txtHeight = document.getElementById('<%= txtHeight.ClientID%>').value;





var blResult = Boolean;
blResult = true;

if (txtcode == "") {
document.getElementById('<%= txtcode.ClientID%>').style.borderColor = "red";
blResult = blResult && false;

}

if (txtgodown == "") {
document.getElementById('<%= txtgodown.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}
 
    if (ddlWarehouse == 0) {
document.getElementById('<%= ddlWarehouse.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}
 
if (txtwidth == "") {
document.getElementById('<%= txtwidth.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}
 
if (txtlenth == "") {
document.getElementById('<%= txtlenth.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}
 
                 
if (txtHeight == "") {
document.getElementById('<%= txtHeight.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}


//alert('hi')
if (blResult == false) {
alert('Please fill the required fields!');
}
return blResult;
}
</script>

<script type="text/javascript">
function ValidateQty() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>  



</asp:Content>
