<%@ Page Title="Bond | Bin Master" Language="VB" MasterPageFile="User.master" AutoEventWireup="false"
CodeFile="LotMaster.aspx.vb" Inherits="Summary_BCYMovement" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
 
    <style type="text/css">
            

.center1 {
text-align: center;
}
</style>
<head>
<title>Bond | Bin Master</title>
       
</head>
<div class="page-container">
<div class="pageheader">
            
<h1>

<i class="glyphicon glyphicon-transfer"></i>Bin Master 
</h1>
           
</div>
       
<div id="page-content">
        
       
       
<asp:ScriptManager ID="ScriptManager1" runat="server">
</asp:ScriptManager>
<asp:UpdatePanel ID="UpdatePanel1" runat="server">
<ContentTemplate>
<div class="page-container" style="margin-left: -5px; margin-right: -5px; margin-top: -15px;">
<asp:Label ID="lblError" runat="server" Text="" ForeColor="red"></asp:Label>
<div class="col-md-3 pull-md-left sidebar" style="padding-top:12px;">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title" style="padding-bottom: 0px !important; ">
<i class="fa fa-cube"></i>&nbsp;   Bin Details
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>   
<div class="panel-body">
<asp:Repeater ID="rptnoLIst" runat="server">
<ItemTemplate>
<div>


<a href='<%# "LotMaster.aspx?EntryIDView=" & Server.UrlEncode(Encrypt(DataBinder.Eval(Container.DataItem, "EntryID")).ToString())%>' target="_blank"><strong>
<asp:Label runat="server" Text='<%#Eval("LotNo")%>' ID="lblNONumber" Style="text-transform: uppercase;"></asp:Label></strong></a>
<br />
<asp:Label runat="server" Text='<%#Eval("AddDate")%>' ID="lblDate" Style="text-transform: uppercase;"></asp:Label>
<br />
Generated By: &nbsp;<asp:Label runat="server" Text='<%#Eval("Users")%>' ID="lbluser" Style="text-transform: uppercase;"></asp:Label>
<br />
<asp:Label runat="server">----------------------------------</asp:Label>
</div>
</ItemTemplate>
</asp:Repeater>
</div>
</div>
                           
</div>
<div class="panel-body">

<div class="row">
                                         
<div class="col-md-9 pull-md-right main-content" >
<fieldset class="register">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">

            
<div class="panel-body">

<div class="row">
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b>Godown Code</b>
<asp:DropDownList ID="ddlgodown" AutoPostBack="true" Style="text-transform: uppercase;" runat="server" OnSelectedIndexChanged="ddlgodown_SelectedIndexChanged" class="form-control text-label">
</asp:DropDownList>
</div>
</div>
    <asp:Panel ID="Panel3" runat="server" Enabled="false">
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b>Center Code</b>
<asp:TextBox ID="txtCenter" Style="text-transform: uppercase" class="form-control text-label" placeholder="Center Code"
runat="server"></asp:TextBox>
</div>
</div>
        </asp:Panel>
</div>
    <asp:Panel ID="Panel2" runat="server" Enabled="false">
<div class="row">
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b>Warehouse Code</b>
<asp:TextBox ID="txtWarehouse" Style="text-transform: uppercase" class="form-control text-label" placeholder="Warehouse Code"
runat="server"></asp:TextBox>
</div>
</div>

<div class="col-md-8 col-xs-12">
<div class="form-group text-label">
<b>Warehouse Description</b>
<asp:TextBox ID="txtWarehouseDesc" Style="text-transform: uppercase" class="form-control text-label" placeholder="Warehouse Description"
TextMode="MultiLine" runat="server"></asp:TextBox>
</div>
</div>

</div>


</asp:Panel>

</div>
</div>

<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title">Add Details
                
<%--<i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>

<div class="panel-body">
<asp:UpdatePanel ID="UpdatePanel2" runat="server" UpdateMode="Conditional">
<ContentTemplate>
<asp:Panel ID="Panel1" runat="server" Enabled="true">

<div class="row">
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b>Storage Bin</b>
<asp:TextBox ID="txtStorage" Style="text-transform: uppercase" class="form-control text-label" placeholder="Storage bin"
runat="server"></asp:TextBox>
</div>
</div>

<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b>Total Capacity of Storage Bin In</b>
<asp:TextBox ID="txtTotalCapacity" Style="text-transform: uppercase" class="form-control text-label" onkeypress="return ValidateQty()" placeholder="Total Capacity  "
runat="server"></asp:TextBox>
</div>
</div>


</div>
<div class="row">
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b>Length</b>
<asp:TextBox ID="txtlenth" Style="text-transform: uppercase" class="form-control text-label" onkeypress="return ValidateQty()" placeholder="Length"
runat="server"></asp:TextBox>
</div>
</div>

<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b>Width</b>
<asp:TextBox ID="txtwidth" Style="text-transform: uppercase" class="form-control text-label" onkeypress="return ValidateQty()" placeholder="Width"
runat="server"></asp:TextBox>
</div>
</div>
<div class="col-sm-1">
<div class="form-group" style="padding-top: 20px">
<asp:Button ID="btnAdd" class="btn btn-primary " runat="server" OnClick="btnAdd_Click"
Text="Add" OnClientClick="return ValidationAdd()" />
</div>

</div>

</div>
</asp:Panel>
</ContentTemplate>
</asp:UpdatePanel>

<div class="row">
<asp:UpdatePanel ID="up_grid" runat="server" UpdateMode="Conditional">
<ContentTemplate>

<div class="row">
<div class="col-lg-12 text-label " style="padding-right: 50px;">
<div class="table-responsive scrolling-table-container" style="margin-left: 28px; margin-right: 0px;">
<asp:GridView ID="grdcontainer" runat="server" ForeColor="Black" CssClass="table table-striped table-bordered table-hover"
AutoGenerateColumns="False" EmptyDataText="No records found!" ShowHeaderWhenEmpty="true">
<PagerStyle BackColor="white" ForeColor="blue" Font-Underline="false" Height="30px" VerticalAlign="Bottom" HorizontalAlign="center" />
<Columns>

<asp:TemplateField HeaderText="Storage" Visible="true"   HeaderStyle-CssClass="center1"   >
<ItemTemplate>

<asp:Label ID="lblStorage" AutoPostBack="true" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "LotNo")%>'>'></asp:Label>

</ItemTemplate>
<ItemStyle HorizontalAlign="center" />

</asp:TemplateField>

<asp:TemplateField HeaderText="Total" Visible="true" HeaderStyle-CssClass="center1">
<ItemTemplate>

<asp:Label ID="lblTotalCapacity" AutoPostBack="true" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "Area")%>'>'></asp:Label>

</ItemTemplate>
<ItemStyle HorizontalAlign="center" />

</asp:TemplateField>

<asp:TemplateField HeaderText="Length" Visible="true" HeaderStyle-CssClass="center1">
<ItemTemplate>

<asp:Label ID="lbllenth" AutoPostBack="true" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "Lenght")%>'>'></asp:Label>

</ItemTemplate>
<ItemStyle HorizontalAlign="center" />

</asp:TemplateField>


<asp:TemplateField HeaderText="Width" Visible="true" HeaderStyle-CssClass="center1">
<ItemTemplate>

<asp:Label ID="lblwidth" AutoPostBack="true" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "Width")%>'>'></asp:Label>

</ItemTemplate>
<ItemStyle HorizontalAlign="center" />

</asp:TemplateField>


</Columns>

</asp:GridView>
</div>
</div>
</div>
</ContentTemplate>
</asp:UpdatePanel>
</div>




</div>


</div>
                       
                
<asp:Label ID="lblentryID" Visible="false" runat="server" Text=""></asp:Label>
<asp:Label ID="lblcode" Visible="false" runat="server" Text=""></asp:Label>
<asp:Label ID="lblagentname" Visible="false" runat="server" Text=""></asp:Label>
             
                      
<div class="row">

<div class="col-md-6 col-xs-12">
<div class="form-group text-label" style="padding-top: 22px;">
<asp:CheckBox ID="chkisActive" runat="server" Checked="true" />
<asp:HiddenField ID="hdlocation" runat="server" Value="0" />
<asp:Label ID="IsActiveLabel" runat="server" AssociatedControlID="chkisActive" CssClass="inline"> Is Active?</asp:Label>
</div>
</div>

</div>
                         
                       
                  
<div class="row">
<div class="col-sm-1">
<div class="form-group" style="padding-top: 15px">
<asp:Button ID="btnSave" class="btn btn-primary " runat="server" OnClick="btnSave_Click"
Text="Save" OnClientClick="return ValidationSave()" />
</div>


</div>

<div class="col-sm-1" style="padding-left: 14px;">
<div class="form-group" style="padding-top: 15px">

<a href="LotMaster.aspx" id="btnclear" runat="server" class="btn btn-primary ">Clear
</a>

</div>


</div>
<div class="col-sm-5 pull-right" style="padding-top:25px;">
<div class="form-group">
<a href="LotSummary.aspx" target="_blank"><b style="color:blue">Click here to view Lot Summary</b> </a>
</div>
</div>

</div>
                               
                         
<div class="modal fade control-label" id="myModalforupdate" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-sm">
<asp:UpdatePanel ID="UpdatePanel3" runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
<ContentTemplate>
<div class="modal-content">
<div class="modal-header">
<center>
<span><i runat="server" id="I3" class="fa fa-5x fa-check-circle-o text-success"></i></span>
<br />
<h4 class="modal-title">

<asp:Label ID="lblSession" CssClass="control-label" Font-Bold="true" runat="server" Text=""></asp:Label></h4>
</center>
</div>
<div class="modal-footer">

<a href="LotMaster.aspx" class="btn btn-info btn-block">OK</a>

</div>
</div>

</ContentTemplate>

</asp:UpdatePanel>
</div>
</div>
               
</fieldset>

</div>
</div>
                               
</div>
                           
                          
                     
                       
                       
</div>
                 
</ContentTemplate>
</asp:UpdatePanel>
</div>
       
         
</div>
   
<script type="text/javascript">
function ValidationSave() {
var ddlgodown = document.getElementById('<%= ddlgodown.ClientID%>').value;
var txtCenter = document.getElementById('<%= txtCenter.ClientID%>').value;


var blResult = Boolean;
blResult = true;

if (ddlgodown == "0") {
document.getElementById('<%= ddlgodown.ClientID%>').style.borderColor = "red";
blResult = blResult && false;

}

if (txtCenter == "") {
document.getElementById('<%= txtCenter.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}




//alert('hi')
if (blResult == false) {
alert('Please fill the required fields!');
}
return blResult;
}
</script>

<script type="text/javascript">
function ValidateQty() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>

<script type="text/javascript">
function ValidationAdd() {

var txtStorage = document.getElementById('<%= txtStorage.ClientID%>').value;
var txtTotalCapacity = document.getElementById('<%= txtTotalCapacity.ClientID%>').value;
var txtwidth = document.getElementById('<%= txtwidth.ClientID%>').value;
var txtlenth = document.getElementById('<%= txtlenth.ClientID%>').value;


var blResult = Boolean;
blResult = true;

if (txtStorage == "") {
document.getElementById('<%= txtStorage.ClientID%>').style.borderColor = "red";
blResult = blResult && false;

}
// alert('hi')
if (txtTotalCapacity == "") {
document.getElementById('<%= txtTotalCapacity.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (txtwidth == "") {
document.getElementById('<%= txtwidth.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}

if (txtlenth == "") {
document.getElementById('<%= txtlenth.ClientID%>').style.borderColor = "red";
blResult = blResult && false;
}




if (blResult == false) {
alert('Please fill the required fields!');
}
return blResult;
}
</script>
   

</asp:Content>
