<%@ Page Title="Bond | PD Account MAster" Language="VB" MasterPageFile="User.master" AutoEventWireup="false"
CodeFile="PDAccountMaster.aspx.vb" Inherits="Summary_BCYMovement" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
 
       
    <head>
<title>Bond |  PD Account Master</title>
       
</head>
<div class="page-container">
<div class="pageheader">
            
<h1>

<i class="glyphicon glyphicon-transfer"></i>PD Account Master 
</h1>
           
</div>
       
<div id="page-content">
        
       
       
<asp:ScriptManager ID="ScriptManager1" runat="server">
</asp:ScriptManager>
<asp:UpdatePanel ID="UpdatePanel1" runat="server">
<ContentTemplate>
<div class="page-container" style="margin-left: -5px; margin-right: -5px; margin-top: -15px;">
<asp:Label ID="lblError" runat="server" Text="" ForeColor="red"></asp:Label>
<div class="col-md-3 pull-md-left sidebar" style="padding-top:12px;">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title" style="padding-bottom: 0px !important; ">
<i class="fa fa-cube"></i>&nbsp;   PD Account Master 
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>   
<div class="panel-body" Style="text-transform:lowercase;">
<asp:Repeater ID="rptnoLIst" runat="server">
<ItemTemplate>
<div  >
                             
                            
<a  href='<%# "PDAccountMaster.aspx?EntryIDView=" & Server.UrlEncode(Encrypt(DataBinder.Eval(Container.DataItem, "EntryID")).ToString())%>' target="_blank" ><strong><asp:Label runat="server"  Text='<%#Eval("AccountName")%>' ID="lblNONumber" style="text-transform:uppercase;"></asp:Label></strong></a>                                                     
<br /> <asp:Label runat="server" Text='<%#Eval("AddDate")%>' Id="lblDate" style="text-transform:uppercase;"></asp:Label>
<br/>Generated By: &nbsp;<asp:Label runat="server" Text='<%#Eval("Users")%>' Id="lbluser" style="text-transform:uppercase;"></asp:Label>
<br />
<asp:Label runat="server" >----------------------------------</asp:Label>
</div>
</ItemTemplate>
</asp:Repeater>
</div>
</div>
                           
</div>
<div class="panel-body">

<div class="row">
                                         
<div class="col-md-9 pull-md-right main-content" >
<fieldset class="register">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">

            
<div class="panel-body">
<asp:Panel ID="Panel2" runat="server" Enabled="true"> 
<div class="row">
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Customer Name</b>
<asp:DropDownList ID="ddlAgency" AutoPostBack="true" Style="text-transform: uppercase;" runat="server"  class="form-control text-label">                                        
</asp:DropDownList> 
</div>
</div>
</div>
<div class="row">
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >PD Code</b>
<asp:TextBox ID="txtpdcode" Style="text-transform:uppercase" class="form-control text-label"  placeholder="PD Code"
runat="server"   ></asp:TextBox>
</div>
</div>
</div>
                               

<div class="row">
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >PD Account Name</b>
<asp:TextBox ID="txtPDAccount" Style="text-transform:uppercase" class="form-control text-label"  placeholder="PD Account Name"
runat="server"   ></asp:TextBox>
</div>
</div>
                                 
</div>

<div class="row">
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >Openning Balance</b>
<asp:TextBox ID="txtopnning" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateQty()"  placeholder="Openning Bal"
runat="server"   ></asp:TextBox>
</div>
</div>
                                 
</div>

<div class="row">
<div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >Credit Limit Amount  </b>
<asp:TextBox ID="txtCredit" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateQty()"  placeholder="Credit Limit Amt"
runat="server"   ></asp:TextBox>
</div>
</div>

<div class="col-md-6 col-xs-12">
<div class="form-group text-label" style="padding-top:22px;">
<asp:CheckBox ID="chkisActive" runat="server" Checked="true" />
<asp:hiddenfield ID="Hiddenfield1" runat="server" Value="0" />
<asp:Label ID="Label1" runat="server" AssociatedControlID="chkisActive" CssClass="inline"> Is Active?</asp:Label>
</div>
</div>

                                 
</div>
 
                               
</asp:Panel>
                        
</div>
</div>
<asp:Label ID="lblentryID" Visible="false" runat="server" Text=""></asp:Label>
<asp:Label ID="lblcode" Visible="false" runat="server" Text=""></asp:Label>
<asp:Label ID="lblagentname" Visible="false" runat="server" Text=""></asp:Label>
             
                      
<div class="row">
<div class="col-sm-1">
<div class="form-group" style="padding-top:15px">
<asp:Button ID="btnSave" class="btn btn-primary " runat="server" OnClick="btnSave_Click"
Text="Save"  OnClientClick="return ValidationSave()" />
</div>
                                              
                                      
</div>
                       
<div class="col-sm-1" style="padding-left:14px;">
<div class="form-group" style="padding-top:15px">
                           
<a href="PDAccountMaster.aspx" id="btnclear" runat="server" class="btn btn-primary ">
Clear
</a> 
                              
</div>
                                              
                                      
</div>
<div class="col-sm-5 pull-right" style="padding-top:25px;">
<div class="form-group">
<a href="PDSummary.aspx" target="_blank"><b style="color:blue">Click here to view PD Account Summary</b> </a>
</div>
</div>
                         
</div>
                   
                         
<div class="modal fade control-label" id="myModalforupdate" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-sm">
<asp:UpdatePanel ID="UpdatePanel3" runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
<ContentTemplate>
<div class="modal-content">
<div class="modal-header">
<center>
<span><i runat="server" id="I3" class="fa fa-5x fa-check-circle-o text-success"></i></span>
<br />
<h4 class="modal-title">

<asp:Label ID="lblSession" CssClass="control-label" Font-Bold="true" runat="server" Text=""></asp:Label></h4>
</center>
</div>
<div class="modal-footer">
                   
<a href="PDAccountMaster.aspx" class="btn btn-info btn-block">OK</a>
                                
</div>
</div>
                    
</ContentTemplate>
             
</asp:UpdatePanel>
</div>
</div>
               
</fieldset>

</div>
</div>
                               
</div>
                           
                          
                     
                       
                       
</div>
                 
</ContentTemplate>
</asp:UpdatePanel>
</div>
       
         
</div>
   
<script type="text/javascript">
function ValidationSave() {
var ddlAgency = document.getElementById('<%= ddlAgency.ClientID%>').value;
                   
               

var blResult = Boolean;
blResult = true;

if (ddlAgency == "0") {
document.getElementById('<%= ddlAgency.ClientID%>').style.borderColor = "red";
blResult = blResult && false;

}
 
//alert('hi')
if (blResult == false) {
alert('Please fill the required fields!');
}
return blResult;
}
</script>

<script type="text/javascript">
function ValidateQty() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>
   

</asp:Content>
